repos:
-   repo: local
    hooks:
    -   id: julia-format
        name: Julia Formatter
        entry: julia_format.jl
        language: script
        files: \.jl$
        types: [file]
        require_serial: true
        description: "Format Julia files using JuliaFormatter.jl"