name: Code Formatting

on:
  push:
    branches:
      - '*'

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
      - uses: julia-actions/setup-julia@latest
      - uses: actions/checkout@v4
        
      - name: Install JuliaFormatter and format
        run: |
            julia  -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter"))'
            julia  -e 'using JuliaFormatter; format(".", verbose=true)'
        
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git diff --quiet || (git add . && git commit -m "Apply automatic formatting" && git push)